version: '3.9'

services:
  fap-api:
    image: ${FAP_IMAGE_NAME:-fap-api:latest}
    container_name: fap-api-container
    restart: always
    ports:
      - "8081:8081"
    networks:
      - fcm-network

  app:
    image: ${IMAGE_NAME:-fcm-backend:latest}
    container_name: fcm-backend-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASE: ${REDIS_DATABASE}
      HOST_FRONT_END: ${HOST_FRONT_END:-http://localhost:5173}
      FAP_API_URL: http://fap-api:8081/api/allowed-users
    depends_on:
      - fap-api
    networks:
      - fcm-network


volumes:
  redis-app-data:

networks:
  fcm-network:
    driver: bridge
    name: fcm-network
