version: '3.9'

services:
  redis:
    image: redis:7.4.0
    container_name: redis-app
    restart: always
    volumes:
      - redis-app-data:/data
    ports:
      - "6379:6379"
    networks:
      - fcm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 128MB

  app:
    image: ${IMAGE_NAME:-fcm-backend:latest}
    container_name: fcm-backend-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: redis-app
      SPRING_REDIS_PORT: 6379
      HOST_FRONT_END: ${HOST_FRONT_END:-http://localhost:5173}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - fcm-network

volumes:
  redis-app-data:

networks:
  fcm-network:
    driver: bridge
    name: fcm-network
